# Generated by Django 3.2.13 on 2024-09-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='Unknown', max_length=25),
        ),
    ]
